### ISSUE TITLE
The swagger schema is not valid for the module

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-cart#28]
12:50:23 Swagger schema validation failed. 
12:50:23   Array items are not unique (indexes 0 and 1) at #/definitions/MethodImplAttributes/enum

![image](https://user-images.githubusercontent.com/7566324/47281231-490d5f00-d5da-11e8-8373-5f8ae8167515.png)

How to reproduce:
Get the resulting swagger doc
http://localhost/admin/docs/VirtoCommerce.cart/v1
Put them into any public online validator  http://apidevtools.org/swagger-parser/online/
or use CLI
swagger-cli.js validate  swagger.json

**Comment by avas** [comment]
The issue was caused by the [`MethodImplAttributes`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodimplattributes?view=netframework-4.7.2) enumeration that contains some members with duplicating values (e.g. `IL` and `Managed` have value 0, `Runtime` and `CodeTypeMask` have value 3, and `Unmanaged` and `ManagedMask` have value 4). These duplicates cause NSwag to include duplicating values to the enum's description while trying to generate Swagger JSON. Changing preferred enum type from `integer` to `string` does not solve the problem. This is probably a bug in NSwag itself.

As a workaround, I tried to make `MethodImplAttributes` disappear from the Swagger JSON (the Cart module itself does not directly use this type, so why is it included to the API documentation?). It is added to the Swagger JSON as a dependency for the `Func<IEvaluationContext, bool>` type, which is the return type of the `PricelistAssignment.Condition` property. So, I've marked this property with `JsonIgnoreAttribute` - according to the documentation for [JsonSchemaGenerator class](https://github.com/RSuter/NJsonSchema/wiki/JsonSchemaGenerator#ignored-properties) used by NSwag, this will prevent the property from being serialized. (In fact, serializing the `Func` does not make sense anyway - it can't be passed between the frontend and the backend, and it won't work after deserialization.)

Here is the Swagger JSON with this fix: [swagger.zip](https://github.com/VirtoCommerce/vc-module-cart/files/2501565/swagger.zip)

**Comment by tatarincev** [comment]
@avas  That would be great!

**Comment by avas** [comment]
So, there are 3 different errors:
1. `$ref values must be RFC3986-compliant percent-encoded URIs`. 
    This happens due to the way Swashbuckle handles generic types: domaindrivendev/Swashbuckle.AspNetCore#752 (the project is different, but the source of the problem and it's solution are the same). The workaround is quite simple, I'll push a PR in some minutes.
2. `Operations must have unique operationIds.` 
    Swashbuckle generates the `operationId` for operations as `{controllerName}_{actionMethodName}`, and Swagger specification requires that ID to be unique. But the `CompletenessController` in the `CatalogPublishingModule` had multiple methods named `EvaluateCompleteness` with different routes and different parameters - this led to multiple actions having the `operationId` equal to `Completeness_EvaluateCompleteness`. I've tried to rename these methods, and it seems to solve the problem.
3. `Equivalent paths are not allowed.`
    This error is probably caused by actions with routes `/api/order/customerOrders/{cartId}` (`OrderModuleController.CreateOrderFromCart`, `HttpPost`) and `/api/order/customerOrders/{id}` (`OrderModuleController.GetById`, `HttpGet`). Swagger specification [treats](https://github.com/swagger-api/swagger-editor/issues/1677) these paths as equivalent, despite of different parameter types and HTTP verbs are different. I don't know how to solve it yet. There might be a way to force Swashbuckle to combine these operations to one entry. But if there isn't such way, fixing this issue might lead to some breaking route changes.

**Comment by avas** [comment]
Created PR for the last issue. Now the JSON generated by the Swashbuckle on my machine seems to pass the validation on https://editor.swagger.io.
[v1.zip](https://github.com/VirtoCommerce/vc-module-cart/files/2515292/v1.zip)

**Comment by GheorgheVolosenco** [comment]
I had the same issue **Array items are not unique (indexes 0 and 1) at #/definitions/MethodImplAttributes/enum**

The problem was, that in one SwaggerResponse Attribute I was using a type from a library and it was causing the problem. 
       [SwaggerResponse((int)HttpStatusCode.OK, Type = typeof(TypeFromLibrary))]

After removing the swagger response attribute(or changing the type response), the issue was solved.

I'd like to mention that this the issue reproduced just on .Net Core 2.1 with Swashbuckle on version 3.0 . 
For .Net Core 2.0, it works well.

**Comment by manisha201301** [comment]
Unfortunately, the above solution doesn't work for me :(
